[build-system]
requires = ["hatchling==1.30.1"]
build-backend = "hatchling.build"

[project]
name = "Questy"
version = "0.0.1"
description = "Personal system"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram==3.30.0",
    "alembic==1.18.4",
    "asyncpg==0.31.0",
    "dishka==1.10.1",
    "fastapi==0.137.1",
    "pydantic==2.13.4",
    "pydantic-settings==2.14.1",
    "sqlalchemy==2.0.51",
    "taskiq==0.12.4",
    "taskiq-redis==1.2.3",
    "uuid6==2025.0.1",
    "uvicorn==0.49.0",
    "email-validator==2.3.0",
    "tzdata==2026.3",
    "argon2-cffi==25.1.0",
]

[dependency-groups]
dev = [
    "pre-commit==4.6.0",
    "ruff",
]

[tool.ruff]
line-length = 120
target-version = "py313"
extend-exclude = ["migrations/versions/*"]

[tool.ruff.lint]
select = [
    "E", "F", "I", "B", "C4", "UP", "ASYNC",
    "ANN", "S", "PTH", "SIM", "TCH", "RUF",
    "FAST", "PYI"
]

ignore = ["D", "ANN401", "B008", "S101", "RUF001", "RUF002", "RUF003"]

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = false
suppress-none-returning = true
suppress-dummy-args = true

[tool.ruff.lint.isort]
known-first-party = ["modules", "integrations", "entrypoints", "shared"]

[tool.hatch.build.targets.wheel]
packages = [
    "src/entrypoints",
    "src/shared",
    "src/integrations",
    "src/modules",
]
